### ISSUE TITLE
Add scrollbars

### ISSUE THREAD

**Issue by esDotDev** [Codelessly/FlutterPubWebsite#2]
The site will feel more web-like if you add scrollbars. 

We have an example here:
https://github.com/gskinnerTeam/flokk/blob/master/flokk_src/lib/styled_components/scrolling/styled_scrollbar.dart

Its quite simple, the Scrollbar and Listview just need to be put in a stack together and given the same ScrollController:
https://github.com/gskinnerTeam/flokk/blob/master/flokk_src/lib/styled_components/scrolling/styled_listview.dart

**Comment by rayliverified** [comment]
Thanks for the resource links.

After a bit of research, I've decided to not add scrollbars because scroll bars appear differently in different browsers.
Scrollbars should be handled natively whenever that happens.

**Comment by esDotDev** [comment]
Agreed in theory, but this is impossible in flutter. So end of the day, you have scrolling content, user has a mouse, they do need a scrollbar if you want good UX.
